language: python

sudo: false
matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
      sudo: true
      dist: xenial

install: travis_retry pip install tox
script: tox

notifications:
  email: false